### ISSUE TITLE
A question about the test stage of Instance-level branch

### ISSUE THREAD

**Issue by hwfan** [DirtyHarryLYL/HAKE-Action#15]
Thanks for your great job on both HOI recognition/detection! I downloaded your code and tried to reproduce your results in the paper, but in the 75L~77L of -Results/Generate_detection.py I felt confused about the details:
```
sP = torch.sigmoid(torch.from_numpy(score_P[obj_index]).cuda()).cpu().numpy() * P_weight
sA = torch.sigmoid(torch.from_numpy(score_A[obj_index]).cuda()).cpu().numpy() * A_weight
sL = torch.sigmoid(torch.from_numpy(score_L[obj_index]).cuda()).cpu().numpy() * L_weight
```
As shown, in your code sP, sA, sL are multiplied with P_weight, A_weight and L_weight respectively. The three weights are defined in 42L:
```
h_fac, o_fac, sp_fac, P_fac, A_fac, L_fac, hthresh, othresh, athresh, bthresh, P_weight, A_weight, L_weight = pickle.load(open('generation_args.pkl', 'rb'))
```
I carefully checked the content of generation_args.pkl and found that **only P_weight has the value of 1.0**, while **A_weight and L_weight are both 1e-5**. And after I removed sA and sL from the final score, **the mAP didn't decrease**, which means both Attention branch and Language branch will not contribute to the final results with the weight 1e-5. 
**Is 1e-5 the best weight that you found? Or did I make anything wrong?** The problem is important since the reproduction of your ablation study strongly relies on this part.

**Comment by Foruck** [comment]
Currently, we mainly exploit the joint training of attention module and language module, while the output score of attention module and language module haven't been fully utilized. Moreover, for different datasets, the best fusion weights could be different, and probably require tuning separately. For simplicity and clarity, we give sA and sL small weights. Tuning the weights might produce higher mAP than reported in our paper. 

As to the ablation study, note that ‘w/o part attention’ means training the whole model without part attention module from scratch, instead of simply ignoring `sA` during test phase. The same is for the language module.

**Comment by hwfan** [comment]
> Currently, we mainly exploit the joint training of attention module and language module, while the output score of attention module and language module haven't been fully utilized. Moreover, for different datasets, the best fusion weights could be different, and probably require tuning separately. For simplicity and clarity, we give sA and sL small weights. Tuning the weights might produce higher mAP than reported in our paper.
> 
> As to the ablation study, note that ‘w/o part attention’ means training the whole model without part attention module from scratch, instead of simply ignoring `sA` during test phase. The same is for the language module.

Special thanks for your detailed replies. Now I'm clear about the mistakes that I made.
Another question about -Results/Generate_detection.py: in 78L you use a score_I which is loaded from another downloaded file, 
```
sHO = (((sH + sO) * ssp + sP + sA + sL) * score_I[im_index[keys[obj_index]], x:y]) * hod
```
and it seems to come from your image-level HICO results, which can increase the final mAP by more than one. 
**Does it mean that with the results of image-level recognition, the information of global context can be better utilized? If so, how should we train the image-level model to reproduce the best result? With your PastaNet or image-level HICO itself?**

**Comment by Foruck** [comment]
The image-level recognition result comes from our Image-level HAKE-Action branch. To reproduce the best result, PaStaNet needs both levels.
Global context information with PaSta involved can provide more constraints and reduce unreasonable predictions. The global prediction is integrated from instance-level model by Multiple Instance Learning (MIL). 
We adopt seperated training because the seperated gradients are easier to converge. 
Unified training of Image-level and Instance-level probably helps boost the performance further, but the balance among different levels and losses should be carefully considered to avoid confilcts.

**Comment by hwfan** [comment]
Thanks for your suggestions. As to the gradient and convergence, I noticed that you train the model by **2M iterations** with **only one GPU**. Did you consider using multi GPUs in one experiment? If there's any official implementation, I hope it can be shown in this repository. (Your released code takes **83 hours** to train a model with only one GPU, and the inofficial multi-GPU implementations of the users of this repository may be also **inaccurate**.)

**Comment by Foruck** [comment]
We are working on the multi-GPU training. We have achieved some the performance gain, but more time is needed for a public access.
