### ISSUE TITLE
Loading checkpoint problem

### ISSUE THREAD

**Issue by anon112233** [DirtyHarryLYL/HAKE-Action#26]
Hello. I am getting a not found error: "NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error: Key pasta_classification/cls_pasta_0/fully_connected/biases not found in checkpoint."

I am using the Test_HICO_DET file and have tried to use the pasta_HICO_DET weights and the pasta_full weights, but both throw the above error.  I am wondering if y'all have updated Weights which I can access or if y'all have any ideas about debugging this problem. Thanks!

**Comment by Foruck** [comment]
Thanks for pointing out. 

This is because some scope names were changed in the code while the checkpoint wasn't changed correspondingly.

To fix this, we add a conversion script [script/convert.py](https://github.com/DirtyHarryLYL/HAKE-Action/blob/Instance-level-HAKE-Action/script/convert.py). You could run 
```Shell
python script/convert.py Weights/pasta_full/HOI_iter_2000000.ckpt <path of the converted ckpt>
``` 
to convert the ckpt and make the variable names match.

**Comment by anon112233** [comment]
Thank you!
